---
- name: "Copy ssl cert for web server"
  copy:
    src: "{{ item.folder }}/{{ item.filename }}"
    dest: "{{ haproxy_dir }}/{{ item.filename }}"
  with_items:
    - "{{ cert_files }}"
  notify:
     - Reload Haproxy configuration

- name: "intialize certs string"
  set_fact:
    certs_strings: ""

- name: "create certs string"
  set_fact:
    certs_strings: "{{ certs_strings }} crt {{ haproxy_dir }}/{{ item.filename }}"
  with_items:
    - "{{ cert_files }}"

- name: "view certs string"
  debug: 
    msg: "{{ certs_strings }}"

- name: "update ssl configuration"
  lineinfile:
    path: "{{ haproxy_dir }}/haproxy.cfg"
    regexp: '(^.*{{ frontend_port }}.*?)\ crt.*(\ no-sslv3.*$)'
    line: '\1{{ certs_strings }}\2'
    backrefs: yes
    state: present
  notify:
     - Reload Haproxy configuration    